- name : Configure Docker on EC2 Instances
  hosts : Production_server
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker _run -itd -p 8085:8081 meenaxim/banking_finance
